[Desktop Entry]
Encoding=UTF-8
Type=Service
Exec=blubb
Comment=Ruby Language Support
Comment[bg]=Поддръжка на езика Ruby
Comment[bs]=Podrška za jezik Ruby
Comment[ca]=Implementació del llenguatge Ruby
Comment[ca@valencia]=Implementació del llenguatge Ruby
Comment[cs]=Podpora jazyka Ruby
Comment[de]=Sprachunterstützung für Ruby
Comment[el]=Υποστήριξη γλώσσας Ruby
Comment[en_GB]=Ruby Language Support
Comment[es]=Implementación del lenguaje Ruby
Comment[et]=Ruby keele toetus
Comment[fi]=Ruby-kielituki
Comment[fr]=Prise en charge du langage Ruby
Comment[ga]=Tacaíocht Ruby
Comment[gl]=Compatibilidade con Ruby
Comment[hne]=रूबी भाखा समर्थन
Comment[hu]=Ruby nyelvi támogatás
Comment[it]=Supporto per il linguaggio Ruby
Comment[ja]=Ruby 言語のサポート
Comment[nds]=Ünnerstütten för Ruby
Comment[nl]=Ondersteuning voor de taal Ruby
Comment[pl]=Obsługa języka Ruby
Comment[pt]=Suporte para a Linguagem Ruby
Comment[pt_BR]=Suporte à linguagem Ruby
Comment[sk]=Podpora jazyka Ruby
Comment[sv]=Stöd för språket Ruby
Comment[tr]=Ruby Dil Desteği
Comment[uk]=Підтримка мови Ruby
Comment[x-test]=xxRuby Language Supportxx
Comment[zh_CN]=Ruby 语言支持
Name=Ruby Support
Name[bg]=Поддръжка на Ruby
Name[bs]=Podrška za jezik Ruby
Name[ca]=Implementació de Ruby
Name[ca@valencia]=Implementació de Ruby
Name[cs]=Podpora Ruby
Name[de]=Unterstützung für Ruby
Name[en_GB]=Ruby Support
Name[es]=Implementación de Ruby
Name[et]=Ruby toetus
Name[fi]=Ruby-tuki
Name[fr]=Prise en charge de Ruby
Name[ga]=Tacaíocht Ruby
Name[gl]=Compatibilidade con Ruby
Name[hu]=Ruby-támogatás
Name[nl]=Ondersteuning voor Ruby
Name[pl]=Obsługa Ruby
Name[pt]=Suporte para Ruby
Name[pt_BR]=Suporte à Ruby
Name[sk]=Podpora Ruby
Name[sv]=Ruby-stöd
Name[tr]=Ruby Desteği
Name[ug]=Ruby قوللىشى
Name[uk]=Підтримка Ruby
Name[x-test]=xxRuby Supportxx
Name[zh_CN]=Ruby 支持
GenericName=Ruby Support
GenericName[bg]=Поддръжка на Ruby
GenericName[bs]=Podrška za jezik Ruby
GenericName[ca]=Implementació de Ruby
GenericName[ca@valencia]=Implementació de Ruby
GenericName[cs]=Podpora Ruby
GenericName[de]=Unterstützung für Ruby
GenericName[el]=Υποστήριξη Ruby
GenericName[en_GB]=Ruby Support
GenericName[es]=Implementación de Ruby
GenericName[et]=Ruby toetus
GenericName[fi]=Ruby-tuki
GenericName[fr]=Prise en charge de Ruby
GenericName[ga]=Tacaíocht Ruby
GenericName[gl]=Compatibilidade con Ruby
GenericName[hne]=रूबी समर्थन
GenericName[hu]=Ruby-támogatás
GenericName[it]=Supporto per Ruby
GenericName[ja]=Ruby サポート
GenericName[nds]=Ruby-Ünnerstütten
GenericName[nl]=Ondersteuning voor Ruby
GenericName[pa]=ਰੂਬੀ ਸਹਿਯੋਗ
GenericName[pl]=Obsługa Ruby
GenericName[pt]=Suporte para Ruby
GenericName[pt_BR]=Suporte à Ruby
GenericName[sk]=Podpora Ruby
GenericName[sv]=Ruby-stöd
GenericName[tr]=Ruby Desteği
GenericName[ug]=Ruby قوللىشى
GenericName[uk]=Підтримка Ruby
GenericName[x-test]=xxRuby Supportxx
GenericName[zh_CN]=Ruby 支持
ServiceTypes=KDevelop/Plugin
Icon=application-x-ruby
X-KDE-Library=kdevrubylanguagesupport
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=Ruby
X-KDevelop-Args=RUBY
X-KDevelop-Interfaces=ILanguageSupport
X-KDevelop-SupportedMimeTypes=application/x-ruby
X-KDE-PluginInfo-Name=KDevRubySupport
X-KDevelop-Mode=NoGUI
X-KDevelop-LoadMode=AlwaysOn
