// THIS FILE IS GENERATED
// WARNING! All changes made in this file will be lost!
#ifndef KDEVRUBY_VERSION_H
#define KDEVRUBY_VERSION_H

#include <kdeversion.h>

#define KDEVRUBY_MAJOR_VERSION @KDEVRUBY_VERSION_MAJOR@
#define KDEVRUBY_MINOR_VERSION @KDEVRUBY_VERSION_MINOR@
#define KDEVRUBY_PATCH_VERSION @KDEVRUBY_VERSION_PATCH@

#define KDEVRUBY_VERSION_STR "@KDEVRUBY_VERSION_MAJOR@.@KDEVRUBY_VERSION_MINOR@.@KDEVRUBY_VERSION_PATCH@"

#define KDEVRUBY_VERSION KDE_MAKE_VERSION(@KDEVRUBY_VERSION_MAJOR@, @KDEVRUBY_VERSION_MINOR@, @KDEVRUBY_VERSION_PATCH@)

#endif
